version: "3"

services:
  mongo_db:
    image: mongo:6.0
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=netshoesStoreDB
    volumes:
      - db:/data/db
    command:
      ["mongod", "--bind_ip_all"]
    networks:
      - mongo-compose-network
volumes:
  db:

networks:
  mongo-compose-network:
    driver: bridge